name: instll-dep-https

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip_install_privates
        pip_install_privates --token ${{ secrets.ACTIONS_PIP_ACCESS_EXAMPLE_PROJECT_TOKEN }} requirements.ssh.txt
